runtime! archlinux.vim


" GENERAL 
set relativenumber
set invnumber 
set autoindent
set tabstop=2
set shiftwidth=2
set scrolloff=5
set clipboard=unnamedplus
let loaded_matchparen = 1 

set formatoptions-=c formatoptions-=r formatoptions-=o

" SEARCHING
set incsearch
set hlsearch 
set shortmess-=S
" set ignorecase 


augroup remember_folds
	autocmd!
	autocmd BufWinLeave * mkview
	autocmd BufWinEnter * silent! loadview
augroup END


" PLUGINS
call plug#begin()
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && npx --yes yarn install' }
Plug 'valloric/youcompleteme'
Plug 'dense-analysis/ale'
call plug#end()

" MarkdownPreview
let g:mkdp_auto_start = 1
let g:mkdp_auto_close = 1

" set to 1, Vim will refresh Markdown when saving the buffer or
" when leaving insert mode. Default 0 is auto-refresh Markdown as you edit or
" move the cursor
" default: 0
let g:mkdp_refresh_slow = 0
let g:mkdp_command_for_global = 0
let g:mkdp_open_to_the_world = 0
let g:mkdp_open_ip = ''
let g:mkdp_browser = ''
let g:mkdp_echo_preview_url = 0
let g:mkdp_preview_options = {
    \ 'mkit': {},
    \ 'katex': {},
    \ 'uml': {},
    \ 'maid': {},
    \ 'disable_sync_scroll': 0,
    \ 'sync_scroll_type': 'middle',
    \ 'hide_yaml_meta': 1,
    \ 'sequence_diagrams': {},
    \ 'flowchart_diagrams': {},
    \ 'content_editable': v:false,
    \ 'disable_filename': 0,
    \ 'toc': {}
    \ }
" use a custom Markdown style. Must be an absolute path
" like '/Users/username/markdown.css' or expand('~/markdown.css')
let g:mkdp_markdown_css = expand('~/.config/vim/markdown-theme/cream.css')
" use a custom highlight style. Must be an absolute path
" like '/Users/username/highlight.css' or expand('~/highlight.css')
let g:mkdp_highlight_css = ''
let g:mkdp_port = ''
let g:mkdp_page_title = '「${name}」'
" let g:mkdp_images_path = /home/user/.markdown_images
let g:mkdp_filetypes = ['markdown']
let g:mkdp_theme = 'dark'
let g:mkdp_combine_preview = 0
let g:mkdp_combine_preview_auto_refresh = 1



" ALE
" let g:ale_lint_on_text_changed = 'normal'
" let g:ale_lint_on_insert_leave = 1
" set signcolumn=number "the '>>' in ALE

augroup markdown_spelling
	autocmd! FileType markdown set spell
augroup END

" HIGHLIGHT CONTRAST PROBLEMS
hi Folded cterm=Bold ctermfg=19
hi MatchParen cterm=Bold ctermfg=19
hi ALEWarning cterm=underline ctermfg=LightRed
hi ALEError cterm=underline ctermfg=LightRed
hi Search cterm=Bold ctermfg=19 ctermbg=230
hi SpellBad cterm=underline,bold ctermfg=Red ctermbg=none

" CURSOR
" hi Cursor cterm=Bold 
" hi iCursor cterm=Bold 
" hi vCursor cterm=Bold 
" hi cCursor cterm=Bold 
" hi vCursor cterm=Bold 


" ESCAPE REMAP
inoremap kj <esc>
vnoremap kj <esc>
cnoremap kj <C-C>

" LINE NUMBER TOGGLE REMAP
" inoremap `` <Esc>:set nonumber! norelativenumber!<Esc>`q

set timeoutlen=400

" FILETYPE SPECIFIC
filetype plugin on
filetype indent on
syntax on

" BRACKET COMPLETION
"inoremap { {}<Esc>ha
"inoremap ( ()<Esc>ha
"inoremap [ []<Esc>ha
"inoremap " ""<Esc>ha
"inoremap ' ''<Esc>ha
"inoremap ` ``<Esc>ha
"inoremap < <><Esc>ha
