# # ~/.bashrc # # If not running interactively, don't do anything [[ $- != *i* ]] && return

export $(envsubst < ~/.env)

if [ "$USER" == 'jshin53' ]; then
	TERM='xterm-color'
fi

source $HOME/.dotfiles/bashrc/aliases
source $HOME/.dotfiles/bashrc/looknfeel
source $HOME/.dotfiles/bashrc/tmux

#################
#   AUTOSTART   #
#################
# fxf
eval "$(fzf --bash)"

# nvm
NVMPATH="/usr/share/nvm/init-nvm.sh"
if test -f "$NVMPATH"; then
	source "$FILE"
fi

clear
cal -3
