# # ~/.bashrc # # If not running interactively, don't do anything [[ $- != *i* ]] && return

export $(envsubst < ~/.env)

if [ "$USER" == 'jshin53' ]; then
	export TERM='xterm-color'
	# have a env var that is unique
	# this var will be referenced throughout all of the configs
	# tmux, vim (no plugins), bash (for term color), setup.sh (to only install the big3)
	# the env will be setup once in this bash config after you git pull depending on the system
	# options: personal, simple
	export JUDEDOTFILETYPE='simple'
fi

source $HOME/.dotfiles/bashrc/aliases
source $HOME/.dotfiles/bashrc/looknfeel
source $HOME/.dotfiles/bashrc/tmux

#################
#   AUTOSTART   #
#################
# fxf
eval "$(fzf --bash)"

# nvm
NVMPATH="/usr/share/nvm/init-nvm.sh"
if test -f "$NVMPATH"; then
	source "$FILE"
fi

clear
cal -3
